### ISSUE TITLE
Support for authentication and headers 

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/pypi.streamsx.inet#2]
How can we use the package to make a request that is authenticated, or to specify headers with the request?

**Comment by joergboe** [comment]
This package exposes only the basic functionality of the HTTPRequest Operator to the python functions. The user is able to connect via http or https to the server and is able to accept self signed certificates in test setups. Is is a considerable effort to support all parameters of the HTTPRequest Operator. Which authentication method is considered essential?

**Comment by natashadsilva** [comment]
I think if you can support specifying headers in general, that is an essential part that is missing and would support both Basic and Token authentication.
Also need to support retrieving the headers from the input Stream and not as a parameter.

**Comment by joergboe** [comment]
This is implemented in release 1.1.0
